home/urls.py
from django.conf.urls import url, include
from . import views
app_name ='home'

urlpatterns = [
    url(r'^$', views.home, name='base'),
    url(r'^searchemp/$', views.searchemp, name='searchemp'),
    url(r'^searchment/$', views.searchment, name='searchment'),
    url(r'^home/$', views.home, name='base'),
    url(r'^base/$', views.home, name='base'),
   #url(r'^home/$', include('omk.urls')),
    url(r'^about/$', views.about, name='about'),
    url(r'^mentor/$', views.mentor, name='mentor'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^index/$', views.index, name='index'),
    url(r'^empindex/$', views.empindex, name='empindex'),
    url(r'^emphome/$', views.emphome, name='emphome'),
    url(r'^mentorhome/$', views.mentorhome, name='mentorhome'),
    url(r'^markattendance/$', views.markattendance, name='markattendance'),
    url(r'^markattendanceedit/$', views.mrkatt_new, name='mrkatt_new'),
    url(r'^studentsreports/$', views.Student_Report, name='studentsreports'),
    url(r'^studentsreportsedit/(?P<pk>\d+)/edit/$', views.Student_Report_Edit, name='Student_Report_Edit'),
    url(r'^createappointments/$', views.createappointments, name='createappointments'),
    url(r'^mentortask/$', views.mentortask, name='mentortask'),
    url(r'^empmarkattendance/$', views.empmarkattendance, name='empmarkattendance'),
    url(r'^empstudentsreports/$', views.Emp_Student_Report, name='empstudentsreports'),
    url(r'^empstudreportedit/(?P<pk>\d+)/edit/$', views.Emp_Student_Report_Edit, name='Emp_Student_Report_Edit'),
    url(r'^empcreateappointments/$', views.empcreateappointments, name='empcreateappointments'),
    url(r'^mentorlist/$', views.mentor_list, name='mentorlist'),
    url(r'^mentoredit/(?P<pk>\d+)/edit/$', views.mentor_edit, name='mentor_edit'),
    url(r'^emptask/$', views.emptask, name='emptask'),
    url(r'^mentorlist/$', views.mentor_list, name='mentorlist'),
    url(r'^mentornew/$', views.mentor_new, name='mentor_new'),
    url(r'^studentlist/$', views.Student_list, name='studentlist'),
    url(r'^mentstudlist/$', views.mentstudlist, name='mentstudlist'),
    url(r'^student/(?P<pk>\d+)/edit/$', views.studentedit, name='studentedit'),
    url(r'^studentsarchive/$', views.studentsarchive, name='studentsarchive'),
    url(r'^studentadd/$', views.studentadd, name='studentadd'),
    url(r'^archive/$', views.archive, name='archive'),
    url(r'^location/$', views.location, name='location'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),
    url(r'^donate/$', views.donation, name='donation'),
    url(r'^thankyou/$', views.thankyou, name='thankyou')
        ]

omk/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views
from django.contrib.auth import views as auth_views

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^About Us/$', views.About_Us, name= 'About_Us'),
    url(r'', include('home.urls')),
    url(r'^accounts/login/$', views.login, name='login'),
    url(r'^accounts/logout/$', views.logout, name='logout', kwargs={'next_page': '/'}),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, name='password_reset_complete'),
    url(r'^oauth/', include('social_django.urls', namespace='social')),

    ]

home/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import ChoiceField, RadioSelect

from .models import Employee, Mentor, Student , ClassName , Attendance

class EmployeeForm(forms.ModelForm):
    class Meta:
         model = Employee
         fields = ('Employee_Id','Employee_name','Employee_phone','Employee_Address',  )



class MentorForm(forms.ModelForm):
    class Meta:
         model = Mentor
         fields = ('Mentor_Id','Mentor_name','Mentor_phone','Mentor_Address' ,'Mentor_Gender' ,'begining_date','ending_date','Mentor_email',)

class StudentForm(forms.ModelForm):
    class Meta:
         model = Student
         fields =('Student_id','Student_name','Student_curr_grade','Student_prev_grade','Student_Class',
                   'Parents_email','Parents_phone','School','Men_name','Emp_name','Comments','start_date','last_date',)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password',]


class ClassNameForm(forms.ModelForm):
      class Meta:
          model = ClassName
          fields=('class_name', 'class_date','Mentor',)
          #attendance= forms.ChoiceField(required=True, widget=forms.RadioSelect(attrs={'class':'Radio'}),choices=(('abscent','Abscent'),('present','Present'),))
class AttendanceForm(forms.ModelForm):
      class Meta:
          model = Attendance
          fields = ('stu_name','attend','attend_date','remarks',)

home/views.py
from django.shortcuts import render

# Create your views here.


from django.http import JsonResponse
from django.utils import timezone
from .models import *
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.contrib.auth.decorators import login_required
from .forms import *
from django.db.models import *
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.db.models import Q
from .models import Student,Mentor,Employee
from .forms import StudentForm,UserForm,EmployeeForm,ClassNameForm


def searchemp(request):
    name_query = request.GET.get("name")
    curr_grade_query = request.GET.get("currgrade")
    prev_grade_query = request.GET.get("prevgrade")

    students = None
    #if (len(name_query) > 0) or (len(curr_grade_query) > 0) or (len(prev_grade_query) > 0):
    #    students = Student.objects.filter(
    #        Q(Student_name__icontains=name_query, Student_curr_grade__icontains=curr_grade_query,Student_prev_grade__icontains=prev_grade_query)).distinct()
    if len(name_query) > 0:
        students = Student.objects.filter(Q(Student_name__icontains=name_query)).distinct()
    #elif len(curr_grade_query) > 0:
    #    students = Student.objects.filter(Q(Student_curr_grade__icontains=curr_grade_query)).distinct()
    #elif len(prev_grade_query) > 0:
    #    students = Student.objects.filter(Q(Student_prev_grade__icontains=prev_grade_query)).distinct()
    else:
        pass
    return render(request, 'home/emphome.html', {'students': students})


def searchment(request):
    name_query = request.GET.get("name")
    curr_grade_query = request.GET.get("currgrade")
    prev_grade_query = request.GET.get("prevgrade")

    students = None
    #if (len(name_query) > 0) or (len(curr_grade_query) > 0) or (len(prev_grade_query) > 0):
    #    students = Student.objects.filter(
    #        Q(Student_name__icontains=name_query, Student_curr_grade__icontains=curr_grade_query,
    #          Student_prev_grade__icontains=prev_grade_query)).distinct()
    if len(name_query) > 0:
        students = Student.objects.filter(Q(Student_name__icontains=name_query)).distinct()
    #elif len(curr_grade_query) > 0:
    #    students = Student.objects.filter(Q(Student_curr_grade__icontains=curr_grade_query)).distinct()
    #elif len(prev_grade_query) > 0:
    #    students = Student.objects.filter(Q(Student_prev_grade__icontains=prev_grade_query)).distinct()
    else:
        pass
    return render(request, 'home/mentorhome.html', {'students': students})


def home(request):
    return render(request, 'home/base.html',
                  {'home': home})

def about(request):
    return render(request, 'home/about.html',
                  {'about': about})


def mentor(request):
    return render(request, 'home/mentor.html',
                  {'mentor': mentor})

def index(request):
    return render(request, 'home/index.html',
                  {'index': index})

def empindex(request):
    return render(request, 'home/empindex.html',
                  {'empindex': empindex})

def emphome(request):
    students = Student.objects.filter(Emp_name__Employee_name=request.user.username).order_by('Student_name')
    return render(request, 'home/emphome.html',
                  {'students': students})

def mentorhome(request):
    students = Student.objects.filter(Men_name__Mentor_name=request.user.username).order_by('Student_name')
    return render(request, 'home/mentorhome.html',
                  {'students':students})


#def studentsreports(request):
#    return render(request, 'home/studentsreports.html',
#                  {'studentsreports': studentsreports})

def createappointments(request):
    return render(request, 'home/createappointments.html',
                  {'createappointments': createappointments})

def mentortask(request):
    return render(request, 'home/mentortask.html',
                  {'mentortask': mentortask})

def empmarkattendance(request):
    return render(request, 'home/empmarkattendance.html',
                  {'empmarkattendance': empmarkattendance})

#def empstudentsreports(request):
#    return render(request, 'home/empstudentsreports.html',
#                  {'empstudentsreports': empstudentsreports})

def empcreateappointments(request):
    return render(request, 'home/empcreateappointments.html',
                  {'empcreateappointments': empcreateappointments})

def emptask(request):
    return render(request, 'home/emptask.html',
                  {'emptask': emptask})

def mentstudlist(request):
    #users = request.user.username()
    students = Student.objects.filter(start_date__lte=timezone.now()).order_by('Student_name')
    return render(request, 'home/mentstudlist.html',
                  {'students': students})



def logout_user(request):
    logout(request)
    form = UserForm(request.POST or None)
    context = {
        "form": form,
    }
    return render(request, 'home/base.html', context)


def login_user(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_staff:
                login(request, user)
                return emphome(request)
            else:
                login(request, user)
                return mentorhome(request)
        else:
            return render(request, 'home/login.html', {'error_message': 'Invalid login'})
    return render(request, 'home/login.html')

def register(request):
    form = UserForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return render(request, 'home/login.html')
    context = {
        "form": form,
    }
    return render(request, 'home/register.html', context)

def password_reset(request):
    return render(request, 'home/password_reset.html',
    {'home': password_reset})


def password_reset_confirm(request):
    return render(request, 'home/password_reset_confirm.html',
    {'home': password_reset_confirm})

def password_reset_email(request):
    return render(request, 'home/password_reset_email.html',
    {'home': password_reset_email})

def password_reset_complete(request):
    return render(request, 'home/password_reset_complete.html',
    {'home': password_reset_complete})

def Student_list(request):
    students = Student.objects.filter(start_date__lte=timezone.now()).order_by('Student_name')
    return render(request, 'home/studentlist.html',
    {'students': students})

def Student_Report(request):
    students = Student.objects.filter(start_date__lte=timezone.now()).order_by('Student_name')
    return render(request, 'home/studentsreports.html',
    {'students': students})

def Emp_Student_Report(request):
    students = Student.objects.filter(start_date__lte=timezone.now()).order_by('Student_name')
    return render(request, 'home/empstudentsreports.html',
    {'students': students})

def Student_Report_Edit(request,pk):
    student = get_object_or_404(Student, pk=pk)
    if request.method == "POST":
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            student = form.save()
            student.updated_date = timezone.now()
            student.save()
            students = Student.objects.filter(start_date__lte=timezone.now()).order_by('Student_name')
            return render(request, 'home/studentsreports.html',
            {'students': students})
    else:
        form = StudentForm(instance=student)
        return render(request, 'home/studreportedit.html', {'form': form})


def Emp_Student_Report_Edit(request,pk):
    student = get_object_or_404(Student,pk=pk)
    if request.method == "POST":
        form = StudentForm(request.POST, instance=student)
        if form.is_valid():
            student = form.save()
            student.updated_date = timezone.now()
            student.save()
            students = Student.objects.filter(start_date__lte=timezone.now()).order_by('Student_name')
            return render(request, 'home/empstudentsreports.html',
            {'students': students})
    else:
        form = StudentForm(instance=student)
        return render(request, 'home/empstudreportedit.html', {'form': form})


def studentedit(request,pk):
   student = get_object_or_404(Student,pk=pk)
   if request.method == "POST":
       form = StudentForm(request.POST, instance=student)
       if form.is_valid():
           student = form.save()
           student.updated_date = timezone.now()
           student.save()
           students = Student.objects.filter(start_date__lte=timezone.now())
           return render(request, 'home/studentlist.html', {'students': students})
   else:
       # print("else")
       form = StudentForm(instance=student)
   return render(request, 'home/studentedit.html', {'form': form})

def studentadd(request):
    if request.method == "POST":
        form = StudentForm(request.POST)
        if form.is_valid():
            student = form.save(commit=False)
            student.start_date = timezone.now()
            student.save()
            students = Student.objects.filter(start_date__lte=timezone.now())
            return render(request, 'home/studentlist.html',
                          {'students': students})

home/templates/home/archive.html
{% extends 'home/empindex.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <h2 style="padding-left: 15Px">Archived Student List</h2>
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Student ID</th>
                <th>Student Name</th>
                <th>Parents Email</th>
                <th>Parents Phone</th>
                <th>School</th>
                <th>Mentor Name</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% now 'Y-m-d' as currt_date %}
            {% for students in students %}
            {% ifequal students.Emp_name|stringformat:"s" user.username %}
                {% if students.last_date|date:"Y-m-d" < currt_date and students.last_date != NULL  %}
                <tr>
                    <td>{{ students.Student_id }}</td>
                    <td>{{ students.Student_name }}</td>
                    <td>{{ students.Parents_email }}</td>
                    <td>{{ students.Parents_phone }}</td>
                    <td>{{ students.School }}</td>
                    <td>{{students.Men_name}}</td>
                    <td><a href="{% url 'home:studentedit' pk=students.pk%}" class="btn btn-warning">Edit</a>
                    </td>
                </tr>

                {% endif %}
            {% endifequal %}
            {% endfor %}
            </tbody>
        </table>

        </div>
        </div>
    </div>
</div>
{% endblock %}

home/templates/home/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>OMAHA MENTOR FOR KIDS</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <header class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">OMK</h3>
              <nav class="nav nav-masthead">
                <a class="nav-link active" href="#">Home</a>
                <a class="nav-link" href="{% url 'home:about' %}">About Us</a>
                <a class="nav-link" href="{% url 'home:login_user' %}">Login</a>
                  <a class="nav-link" href="{% url 'home:donation' %}">Donate</a>
                <a class="nav-link" href="{% url 'home:location' %}">Locate Us</a>
              </nav>
            </div>
          </header>

            <main role="main" class="inner cover">
  <h1 class="cover-heading">OMAHA MENTOR FOR KIDS</h1>
  <p class="lead"></p>
  <p class="lead">
    <a href="{% url 'home:about' %}" class="btn btn-lg btn-secondary">Learn more</a>
  </p>
</main>


            <footer class="mastfoot">
            <div class="inner">
              <p>Contact Us at  <a href="omkidsorg@gmail.com">omkidsorg@gmail.com </a>.</p>
            </div>
          </footer>

        </div>

      </div>
      {% block body %}
      {% endblock %}
    </div>

  </body>
</html>

home/templates/home/donate.html
{% load staticfiles %}

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../../../favicon.ico">

    <title>OMAHA MENTOR FOR KIDS</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">


            <div class="inner">
              <h3 class="masthead-brand">OMK</h3>
              <nav class="nav nav-masthead">
                <a class="nav-link" href="{% url 'home:base' %}">Home</a>
                <a class="nav-link " href="{% url 'home:about' %}">About Us</a>
                <a class="nav-link" href="{% url 'home:login_user' %}">Login</a>
                  <a class="nav-link active" href="{% url 'home:donation' %}">Donate</a>
                <a class="nav-link" href="{% url 'home:location' %}">Locate Us</a>
              </nav>
            </div>

        <br class="container">
           <br>
            <br></br>
            <br></br>

            <ul style="list-style-type:square">
          <h2>Donate</h2>
            <p>Partnership 4 Kids is dedicated to keeping students engaged in learning from kindergarten to careers, but we need your help!
                Without the generosity of supporters like you, our student programs could not exist. You can become a P4K contributing partner in a variety of ways, but regardless of how you choose to give, your contribution will keep more deserving students continuing on the pathway to success!</p>

              <br/>
            <p><strong>-- Click Donate button to make a Donation --</strong></p>
            <ul style="list-style-type:square">
            <form action="https://www.sandbox.paypal.com/cgi-bin/webscr" method="post" target="_top">
                <input type="hidden" name="cmd" value="_s-xclick">
                <input type="hidden" name="hosted_button_id" value="B2MCLL8XU7FWA">
                <input type="image" src="https://www.sandbox.paypal.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
                <img alt="" border="0" src="https://www.sandbox.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
            </form>
            </ul>
           <br/>

              <p>Contact Us at  <a href="omkidsorg@gmail.com">omkidsorg@gmail.com </a>.</p>

        </div>
      </div>

    </div>

  </body>

home/templates/home/empstudentsreports.html
{% extends 'home/empindex.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <h2 style="padding-left: 15Px">Students Report Information</h2>
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Student ID</th>
                <th>Student Name</th>
                <th>Student Class</th>
                <th>Student Prev Grade</th>
                <th>Student Current Grade</th>
                <th>Comments</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>

            {% for students in students %}
                {% ifequal students.Emp_name|stringformat:"s" user.username %}
                <tr>
                    <td>{{ students.Student_id }}</td>
                    <td>{{ students.Student_name }}</td>
                    <td>{{ students.Student_Class }}</td>
                    <td>{{ students.Student_prev_grade }}</td>
                    <td>{{ students.Student_curr_grade }}</td>
                    <td>{{ students.Comments }}</td>
                    <td><a href="{% url 'home:Emp_Student_Report_Edit' pk=students.pk%}" class="btn btn-warning">Edit</a>
                </tr>
                {% endifequal %}
            {% endfor %}
            </tbody>
        </table>
        </div>
        </div>
    </div>
</div>
{% endblock %}

home/templates/home/empstudreportedit.html
{% extends 'home/empindex.html' %}

{% block content %}
    <h1>Edit Student Information</h1>
    <form method="POST" class="student-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default btn-primary">Update</button>
    </form>
{% endblock %}

home/templates/home/home.html
{% extends 'home/base.html' %}

<main role="main" class="inner cover">
  <h1 class="cover-heading">Cover your page.</h1>
  <p class="lead">Cover is a one-page template for building simple and beautiful home pages. Download, edit the text, and add your own fullscreen background photo to make it your own.</p>
  <p class="lead">
    <a href="#" class="btn btn-lg btn-secondary">Learn more</a>
  </p>
</main>




home/templates/home/login.html
{% extends 'home/base_visitor.html' %}
{% block title %}Log In{% endblock %}
{% block login_active %}active{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="container">
            <div class="panel panel-default">
                <div class="lead">
				<div class="col-sm-offset-2 col-sm-12">
                    <h3>Log In</h3><br/>
				</div>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'home:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group" >
							<div class="col-sm-offset-2 col-sm-12">
                            <label  for="id_username">Username: </label>&nbsp;&nbsp;&nbsp;&nbsp;
							<input id="id_username" maxlength="30" name="username" type="text">
							</div>
                        </div>
						
                        <div class="form-group">
							<div class="col-sm-offset-2 col-sm-12">
                            <label for="id_password">Password: </label>&nbsp;&nbsp;&nbsp&nbsp
                            <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-12">
                                <button type="submit" class="btn btn-group-sm btn-secondary">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="col-sm-offset-2 col-sm-12">
                    <a href="{% url 'password_reset' %}"> Reset Password</a> here.
                </div>
                <p><strong>-- OR --</strong></p>

                    <a href="{% url 'social:begin' 'twitter' %}" class="btn-sm btn-info"> Login with Twitter</a>
                </div>
            </div>
        </div>
    </div>

</div>

{% endblock %}


home/templates/home/markattendanceedit.html
{% extends 'home/index.html' %}

{% block content %}
    <h1>Student Attendance</h1>
    <form method="POST" class="attendance-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default btn-primary">Submit</button>
    </form>
{% endblock %}

home/templates/home/mentstudlist.html
{% extends 'home/index.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <h2 style="padding-left: 15Px">Student Information</h2>
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Student ID</th>
                <th>Student Name</th>
                <th>Parents Email</th>
                <th>Parents Phone</th>
                <th>School</th>
            </tr>
            </thead>
            <tbody>

            {% for students in students %}
            {% ifequal students.Men_name|stringformat:"s" user.username %}
                <tr>
                    <td>{{ students.Student_id }}</td>
                    <td>{{ students.Student_name }}</td>
                    <td>{{ students.Parents_email }}</td>
                    <td>{{ students.Parents_phone }}</td>
                    <td>{{ students.School }}</td>
                </tr>
            {% endifequal %}
            {% endfor %}


            </tbody>
        </table>
        </div>
        </div>
    </div>
	</div>

{% endblock %}

home/templates/home/studentedit.html
{% extends 'home/empindex.html' %}

{% block content %}
    <h1>Edit Student</h1>
    <form method="POST" class="student-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-primary">Update</button>
    </form>
{% endblock %}

home/templates/home/studentsarchive.html
{% extends 'home/empindex.html' %}

{% block content %}
    <h1>Archive Student</h1>
    <form method="POST" class="student-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

home/templates/home/studentsreports.html
{% extends 'home/index.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <h2 style="padding-left: 15Px">Students Report Information</h2>
    <div class="table-responsive">
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Student ID</th>
                <th>Student Name</th>
                <th>Student Class</th>
                <th>Student Prev Grade</th>
                <th>Student Current Grade</th>
                <th>Comments</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for students in students %}
                {% ifequal students.Men_name|stringformat:"s" user.username %}
                <tr>
                    <td>{{ students.Student_id }}</td>
                    <td>{{ students.Student_name }}</td>
                    <td>{{ students.Student_Class }}</td>
                    <td>{{ students.Student_prev_grade }}</td>
                    <td>{{ students.Student_curr_grade }}</td>
                    <td>{{ students.Comments }}</td>
                    <td><a href="{% url 'home:Student_Report_Edit' pk=students.pk%}" class="btn btn-warning">Edit</a>
                </tr>
                {% endifequal %}
            {% endfor %}
            </tbody>
        </table>
        </div>
        </div>
    </div>
</div>
{% endblock %}